# Generated by Django 5.2.4 on 2025-07-21 12:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerModels',
            new_name='AnswerModel',
        ),
        migrations.RenameModel(
            old_name='QuestionModels',
            new_name='QuestionModel',
        ),
        migrations.RenameModel(
            old_name='ResponseModels',
            new_name='ResponseModel',
        ),
        migrations.RenameModel(
            old_name='SurveyModels',
            new_name='SurveyModel',
        ),
    ]
