# Generated by Django 5.2.4 on 2025-07-21 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_rename_answermodels_answermodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='required',
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('mcq', 'Multiple Choice')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveymodel'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
